name: Test Errsole Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - run: npm install

      # Run tests with coverage
      - run: npm test -- --coverage
        continue-on-error: false
